# 1단계: build
FROM node:18 AS build

WORKDIR /app

# npm 패키지 복사
COPY package*.json ./

# 의존성 설치
RUN npm install

# 소스 복사
COPY . .

# 빌드 모드 인자를 받아서 실행 (기본 production)
ARG BUILD_MODE=kubernetes

# 빌드 실행
RUN npm run build -- --mode $BUILD_MODE

# 2단계: Nginx 서빙
FROM nginx:alpine

# 빌드된 정적 파일 복사
COPY --from=build /app/dist /usr/share/nginx/html

# (필요시) nginx.conf 커스터마이징
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
